"""create frozen smriti tables schema

Revision ID: c23df1b9fcf0
Revises: 1494a02ffe79
Create Date: 2026-09-02 02:04:13.468483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c23df1b9fcf0'
down_revision: Union[str, Sequence[str], None] = '1494a02ffe79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=True)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('community', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('emotional_risk_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_activity_id'), 'content_items', ['activity_id'], unique=False)
    op.create_index(op.f('ix_content_items_community'), 'content_items', ['community'], unique=False)
    op.create_index(op.f('ix_content_items_id'), 'content_items', ['id'], unique=False)
    op.create_index(op.f('ix_content_items_language'), 'content_items', ['language'], unique=False)
    op.create_table('adaptation_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('support_level', sa.Integer(), nullable=False),
    sa.Column('challenge_level', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('consecutive_struggles', sa.Integer(), nullable=False),
    sa.Column('baseline_response_time_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptation_states_activity_id'), 'adaptation_states', ['activity_id'], unique=False)
    op.create_index(op.f('ix_adaptation_states_id'), 'adaptation_states', ['id'], unique=False)
    op.create_index(op.f('ix_adaptation_states_session_id'), 'adaptation_states', ['session_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('dwell_time_ms', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_activity_id'), 'interactions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_interactions_content_id'), 'interactions', ['content_id'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_session_id'), 'interactions', ['session_id'], unique=False)
    op.create_table('adaptation_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('interaction_id', sa.String(), nullable=False),
    sa.Column('previous_support_level', sa.Integer(), nullable=False),
    sa.Column('new_support_level', sa.Integer(), nullable=False),
    sa.Column('previous_challenge_level', sa.Integer(), nullable=False),
    sa.Column('new_challenge_level', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptation_decisions_activity_id'), 'adaptation_decisions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_adaptation_decisions_id'), 'adaptation_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_adaptation_decisions_interaction_id'), 'adaptation_decisions', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_adaptation_decisions_session_id'), 'adaptation_decisions', ['session_id'], unique=False)
    op.add_column('caregivers', sa.Column('name', sa.String(), nullable=False))
    op.add_column('caregivers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('caregivers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('caregivers', 'full_name')
    op.drop_column('caregivers', 'hashed_password')
    op.add_column('patients', sa.Column('display_name', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('preferred_language', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('community', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_patients_caregiver_id'), 'patients', ['caregiver_id'], unique=False)
    op.drop_column('patients', 'is_active')
    op.drop_column('patients', 'cognitive_tier_baseline')
    op.drop_column('patients', 'alias_name')
    op.add_column('sessions', sa.Column('current_activity_id', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'activities', ['current_activity_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sessions', 'interaction_metrics_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('interaction_metrics_log', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'current_activity_id')
    op.add_column('patients', sa.Column('alias_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('cognitive_tier_baseline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_patients_caregiver_id'), table_name='patients')
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'community')
    op.drop_column('patients', 'preferred_language')
    op.drop_column('patients', 'display_name')
    op.add_column('caregivers', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('caregivers', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('caregivers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('caregivers', 'updated_at')
    op.drop_column('caregivers', 'name')
    op.drop_index(op.f('ix_adaptation_decisions_session_id'), table_name='adaptation_decisions')
    op.drop_index(op.f('ix_adaptation_decisions_interaction_id'), table_name='adaptation_decisions')
    op.drop_index(op.f('ix_adaptation_decisions_id'), table_name='adaptation_decisions')
    op.drop_index(op.f('ix_adaptation_decisions_activity_id'), table_name='adaptation_decisions')
    op.drop_table('adaptation_decisions')
    op.drop_index(op.f('ix_interactions_session_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_content_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_activity_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_adaptation_states_session_id'), table_name='adaptation_states')
    op.drop_index(op.f('ix_adaptation_states_id'), table_name='adaptation_states')
    op.drop_index(op.f('ix_adaptation_states_activity_id'), table_name='adaptation_states')
    op.drop_table('adaptation_states')
    op.drop_index(op.f('ix_content_items_language'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_community'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_activity_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
